apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: ubuntu:16.04
    name: ubuntu
    workingDir: /root/ibm
    volumeMounts:
    - mountPath: /root/ibm
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
