apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  hostNetwork: true
  containers:
  - args:
    - sleep
    - infinity
    image: ubuntu:16.04
    name: ubuntu
    workingDir: /host
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
