apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntu
    workingDir: /host
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
